<?php

require __DIR__.'/vendor/autoload.php';

$app = require_once __DIR__.'/bootstrap/app.php';
$app->make('Illuminate\Contracts\Console\Kernel')->bootstrap();

use App\Models\PromptLibraryPrompt;
use App\Models\Tag;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

// Tạo user admin nếu chưa có
$admin = \App\Models\User::firstOrCreate(
    ['email' => 'admin@lsts.edu.vn'],
    [
        'name' => 'Admin User',
        'password' => Hash::make('changeme-'.uniqid()),
        'initials' => 'AD',
        'role' => 'Admin',
        'department' => 'Administration',
    ]
);
$adminId = $admin->id;

echo "Admin user ID: $adminId\n";

// 215 prompts data
$newPrompts = [
    // === ADMIN (25) ===
    ['title' => 'Weekly Admin Meeting Agenda Generator', 'description' => 'Tạo agenda họp ban giám hiệu / tổ trưởng chuyên môn hàng tuần.', 'preview' => 'Generate a professional weekly admin meeting agenda for a Vietnamese secondary school (grades 6–12). Include: Date & time, Attendees, 5–7 agenda items (school operations, academic progress, events, teacher support, parent communication), Time allocation for each item, Person-in-charge, Follow-up actions from previous meeting. Write in clear Vietnamese and English side-by-side.', 'uses' => 0, 'tags' => [['name'=>'Admin','cat'=>'subject'],['name'=>'New','cat'=>'status']]],
    ['title' => 'Teacher Observation Feedback Template', 'description' => 'Tạo mẫu nhận xét giờ dạy theo chuẩn LSTS.', 'preview' => 'Create a structured classroom observation feedback form for secondary school teachers. Sections: 1. Lesson objectives clarity 2. Student engagement strategies 3. Differentiation 4. Assessment for learning 5. Classroom management 6. Strengths (3 bullet points) 7. Areas for growth (2–3 points) 8. Specific actionable recommendations. Use professional, constructive language. Output in Vietnamese.', 'uses' => 0, 'tags' => [['name'=>'Admin','cat'=>'subject']]],
    ['title' => 'Parent Communication Script – Sensitive Issues', 'description' => 'Soạn kịch bản trao đổi với phụ huynh về vấn đề nhạy cảm.', 'preview' => 'Write a professional, empathetic phone/Zoom script for school administrators to communicate sensitive issues (academic underperformance, behavioral concerns, mental health) with Vietnamese parents. Include: Opening greeting, Clear but gentle statement of concern, Evidence-based observations, Collaborative next steps, Closing with support offer. Provide both Vietnamese and English versions.', 'uses' => 50, 'tags' => [['name'=>'Admin','cat'=>'subject'],['name'=>'Popular','cat'=>'status']]],
    ['title' => 'School Event Planning Checklist', 'description' => 'Tạo checklist tổ chức sự kiện trường học.', 'preview' => 'Create a comprehensive checklist for organizing a school event (e.g. sports day, cultural festival, parent meeting) at a Vietnamese secondary school. Include phases: Planning, Preparation, Execution, Post-event. List responsible roles, timeline, budget considerations, risk assessment, and communication plan. Output in Vietnamese.', 'uses' => 0, 'tags' => [['name'=>'Admin','cat'=>'subject']]],
    ['title' => 'Staff Professional Development Plan Template', 'description' => 'Mẫu kế hoạch bồi dưỡng chuyên môn cho giáo viên.', 'preview' => 'Generate a professional development plan template for secondary school teachers. Include: Individual goal setting, Preferred learning modes, Timeline (semester-based), Resources needed, Success indicators, Reflection section. Write in Vietnamese, suitable for LSTS context.', 'uses' => 0, 'tags' => [['name'=>'Admin','cat'=>'subject']]],
    ['title' => 'Crisis Communication Message Generator', 'description' => 'Soạn thông báo khủng hoảng gửi phụ huynh / giáo viên.', 'preview' => 'Draft a clear, calm, and professional crisis communication message for parents and staff regarding [SITUATION]. Include: What happened (facts only), Actions the school is taking, What parents/staff should do, Contact information. Tone: reassuring and transparent. Provide Vietnamese version first.', 'uses' => 0, 'tags' => [['name'=>'Admin','cat'=>'subject']]],
    ['title' => 'Annual School Calendar Generator', 'description' => 'Tạo khung lịch năm học với các mốc quan trọng.', 'preview' => 'Create an annual school calendar outline for a Vietnamese secondary school (August–June). Include: Academic terms and holidays, Major school events, Assessment periods, Parent meeting windows, Professional development days, Public holidays in Vietnam. Format as a clean monthly list.', 'uses' => 0, 'tags' => [['name'=>'Admin','cat'=>'subject']]],
    ['title' => 'Teacher Workload Audit Questions', 'description' => 'Bộ câu hỏi khảo sát khối lượng công việc giáo viên.', 'preview' => 'Generate a set of 12–15 questions to audit teacher workload in a secondary school. Cover teaching hours, preparation time, administrative tasks, extracurricular duties, and well-being impact. Include both closed and open-ended questions. Output in Vietnamese.', 'uses' => 0, 'tags' => [['name'=>'Admin','cat'=>'subject']]],
    ['title' => 'New Staff Onboarding Checklist', 'description' => 'Checklist tiếp nhận giáo viên / nhân sự mới.', 'preview' => 'Create a detailed onboarding checklist for new teachers and staff at a Vietnamese secondary school. Cover: first day, first week, first month. Include documents, school culture introduction, system access, mentor assignment, and key contacts.', 'uses' => 0, 'tags' => [['name'=>'Admin','cat'=>'subject']]],
    ['title' => 'Budget Justification Paragraph Generator', 'description' => 'Viết đoạn giải trình ngân sách.', 'preview' => 'Write a professional budget justification paragraph for a school proposal requesting funds for [ITEM/PROJECT]. Include need, expected impact on students/teachers, cost-benefit, and alignment with school goals. Keep concise and formal. Vietnamese version.', 'uses' => 0, 'tags' => [['name'=>'Admin','cat'=>'subject']]],
    ['title' => 'School Policy Summary for Parents', 'description' => 'Tóm tắt chính sách trường cho phụ huynh.', 'preview' => 'Summarize the following school policy into clear, parent-friendly language (max 250 words): [PASTE POLICY]. Use simple Vietnamese, bullet points where helpful, and highlight what parents need to know and do.', 'uses' => 0, 'tags' => [['name'=>'Admin','cat'=>'subject']]],
    ['title' => 'Meeting Minutes Auto-Summarizer', 'description' => 'Tóm tắt biên bản họp.', 'preview' => 'Summarize the following meeting notes into structured minutes. Include: Date, Attendees, Key decisions, Action items (with owner and deadline), Open issues. Keep professional and concise. Input notes: [PASTE NOTES].', 'uses' => 0, 'tags' => [['name'=>'Admin','cat'=>'subject']]],
    ['title' => 'Performance Review Comment Bank', 'description' => 'Ngân hàng nhận xét đánh giá hiệu suất.', 'preview' => 'Create a bank of professional performance review comments for secondary school staff in these areas: Teaching quality, Collaboration, Professional growth, Student support, Initiative. Provide 4–5 positive and 3 constructive comments for each area. Vietnamese.', 'uses' => 0, 'tags' => [['name'=>'Admin','cat'=>'subject']]],
    ['title' => 'Student Attendance Intervention Plan', 'description' => 'Kế hoạch can thiệp chuyên cần.', 'preview' => 'Design a tiered attendance intervention plan for secondary students. Include: early warning indicators, Level 1–3 interventions, roles of homeroom teacher / counselor / admin, parent involvement, and documentation template.', 'uses' => 0, 'tags' => [['name'=>'Admin','cat'=>'subject']]],
    ['title' => 'Facility Maintenance Request Template', 'description' => 'Mẫu yêu cầu bảo trì cơ sở vật chất.', 'preview' => 'Create a clear facility maintenance request form for teachers and staff. Fields: Location, Description of issue, Urgency level, Photo attachment note, Requested by, Date. Add sample filled examples.', 'uses' => 0, 'tags' => [['name'=>'Admin','cat'=>'subject']]],
    ['title' => 'External Partner Collaboration Proposal', 'description' => 'Đề xuất hợp tác với đối tác bên ngoài.', 'preview' => 'Write a short collaboration proposal (300–400 words) from LSTS to an external partner (company/university/NGO) for [PURPOSE]. Include school background, mutual benefits, proposed activities, and next steps. Formal Vietnamese.', 'uses' => 0, 'tags' => [['name'=>'Admin','cat'=>'subject']]],
    ['title' => 'School Website Content Update Draft', 'description' => 'Soạn nội dung cập nhật website trường.', 'preview' => 'Draft website content for the following section: [SECTION NAME]. Audience: parents and prospective students. Tone: professional, warm, clear. Length: 150–250 words. Include key information and call-to-action.', 'uses' => 0, 'tags' => [['name'=>'Admin','cat'=>'subject']]],
    ['title' => 'End-of-Year Admin Report Outline', 'description' => 'Dàn ý báo cáo tổng kết năm học.', 'preview' => 'Create a detailed outline for an end-of-year administrative report for a secondary school. Sections: Academic outcomes, Student well-being, Staff development, Events & community, Challenges & recommendations, Data highlights.', 'uses' => 0, 'tags' => [['name'=>'Admin','cat'=>'subject']]],
    ['title' => 'Teacher Recognition Message Generator', 'description' => 'Soạn tin nhắn / thư ghi nhận giáo viên.', 'preview' => 'Write a warm, specific recognition message for a teacher who [ACHIEVEMENT]. Keep authentic and professional. Provide both short (for announcement) and longer (for personal note) versions. Vietnamese.', 'uses' => 0, 'tags' => [['name'=>'Admin','cat'=>'subject']]],
    ['title' => 'Parent-Teacher Conference Schedule Optimizer', 'description' => 'Tối ưu lịch họp phụ huynh.', 'preview' => 'Suggest an efficient parent-teacher conference schedule for a secondary school with [NUMBER] students and [NUMBER] teachers. Consider time slots, rotation, online/offline options, and communication plan.', 'uses' => 0, 'tags' => [['name'=>'Admin','cat'=>'subject']]],
    ['title' => 'Risk Assessment Form for School Trips', 'description' => 'Mẫu đánh giá rủi ro cho chuyến đi.', 'preview' => 'Create a risk assessment form for school trips. Include: Trip details, Potential hazards, Likelihood & severity, Control measures, Emergency contacts, Approval section. Suitable for Vietnamese secondary school context.', 'uses' => 0, 'tags' => [['name'=>'Admin','cat'=>'subject']]],
    ['title' => 'Internal Circular Drafting', 'description' => 'Soạn thông báo nội bộ.', 'preview' => 'Draft an internal school circular about [TOPIC]. Include: Purpose, Key information, Actions required, Deadline, Contact person. Formal but clear Vietnamese.', 'uses' => 0, 'tags' => [['name'=>'Admin','cat'=>'subject']]],
    ['title' => 'Data Dashboard Interpretation Guide', 'description' => 'Hướng dẫn đọc dữ liệu dashboard nhà trường.', 'preview' => 'Write a short guide for school leaders on how to interpret key data from a school dashboard (attendance, academic progress, well-being indicators). Include what to look for, possible questions to ask, and suggested follow-up actions.', 'uses' => 0, 'tags' => [['name'=>'Admin','cat'=>'subject']]],
    ['title' => 'Staff Well-being Survey Analysis', 'description' => 'Phân tích kết quả khảo sát sức khỏe tinh thần nhân sự.', 'preview' => 'Analyze the following staff well-being survey results: [PASTE DATA SUMMARY]. Identify key themes, strengths, areas of concern, and recommend 3–5 practical actions the school can take.', 'uses' => 0, 'tags' => [['name'=>'Admin','cat'=>'subject']]],
    ['title' => 'Leadership Reflection Journal Prompts', 'description' => 'Câu hỏi phản tư dành cho ban lãnh đạo.', 'preview' => 'Generate 10 deep reflection prompts for school leaders focusing on decision-making, culture building, teacher support, and personal leadership growth. Suitable for weekly journal.', 'uses' => 0, 'tags' => [['name'=>'Admin','cat'=>'subject']]],

    // === CIEC / STEAM (28) ===
    ['title' => 'Design Thinking Project Brief Generator', 'description' => 'Tạo brief dự án Design Thinking.', 'preview' => 'Generate a complete Design Thinking project brief for secondary students (grades 6–12) on the topic: [TOPIC]. Include: Empathy stage guiding questions, Define problem statement (How Might We), Ideation techniques, Prototype suggestions (low-cost materials), Testing plan, Reflection questions. Align with CIEC innovation goals. Output in Vietnamese + English.', 'uses' => 0, 'tags' => [['name'=>'CIEC','cat'=>'subject'],['name'=>'UBD','cat'=>'framework'],['name'=>'New','cat'=>'status']]],
    ['title' => 'STEAM Challenge Card Generator', 'description' => 'Tạo thẻ thử thách STEAM ngắn.', 'preview' => 'Create 5 STEAM Challenge Cards for [GRADE] students. Each card must include: Title & time limit, Materials list (common school items), Challenge statement, Success criteria, Extension for advanced students, Reflection question. Theme: [THEME].', 'uses' => 60, 'tags' => [['name'=>'STEAM','cat'=>'subject'],['name'=>'KUD','cat'=>'framework'],['name'=>'Popular','cat'=>'status']]],
    ['title' => 'Innovation Pitch Deck Outline for Students', 'description' => 'Hướng dẫn làm pitch deck 5–7 slides.', 'preview' => 'Generate a student-friendly pitch deck outline (5–7 slides) for a CIEC innovation project. For each slide provide: Slide title, Key content points, Suggested visuals, Speaker notes tips. Focus on problem–solution–impact structure. Write in simple Vietnamese.', 'uses' => 0, 'tags' => [['name'=>'CIEC','cat'=>'subject']]],
    ['title' => 'Prototyping Material Alternatives List', 'description' => 'Gợi ý vật liệu prototype giá rẻ.', 'preview' => 'Suggest low-cost, easily available prototyping materials for secondary students working on [PROJECT TYPE]. Categorize by function (structure, mechanism, aesthetics, electronics). Include where to find them in Vietnam and safety notes.', 'uses' => 0, 'tags' => [['name'=>'STEAM','cat'=>'subject']]],
    ['title' => 'Empathy Interview Question Bank', 'description' => 'Ngân hàng câu hỏi phỏng vấn thấu cảm.', 'preview' => 'Create a bank of 15 empathy interview questions for students conducting user research on [PROBLEM AREA]. Include warm-up, experience, emotion, and ideal-solution questions. Suitable for grades 8–12.', 'uses' => 0, 'tags' => [['name'=>'CIEC','cat'=>'subject']]],
    ['title' => 'Failure Reflection Protocol', 'description' => 'Quy trình phản tư khi prototype thất bại.', 'preview' => 'Design a short failure reflection protocol for student innovation teams. Include: What happened, What we learned, What we will change next, Team appreciation. Keep positive and growth-oriented. Vietnamese.', 'uses' => 0, 'tags' => [['name'=>'CIEC','cat'=>'subject']]],
    ['title' => 'Cross-disciplinary STEAM Unit Planner', 'description' => 'Lập kế hoạch đơn vị học STEAM liên môn.', 'preview' => 'Plan a 4–6 week interdisciplinary STEAM unit for grade [GRADE] around the theme [THEME]. Map connections between Science, Technology, Engineering, Arts, Math. Include driving question, key activities, and final product.', 'uses' => 0, 'tags' => [['name'=>'STEAM','cat'=>'subject'],['name'=>'UBD','cat'=>'framework']]],
    ['title' => 'Maker Space Safety Rules Generator', 'description' => 'Nội quy an toàn không gian sáng tạo.', 'preview' => 'Create a clear, student-friendly set of Maker Space safety rules for a secondary school. Cover tools, materials, behavior, emergency procedures. Use positive language and icons suggestions.', 'uses' => 0, 'tags' => [['name'=>'STEAM','cat'=>'subject']]],
    ['title' => 'Student Innovation Portfolio Rubric', 'description' => 'Rubric đánh giá portfolio sáng tạo.', 'preview' => 'Create a rubric for assessing student innovation portfolios. Criteria: Process documentation, Empathy evidence, Iteration, Final prototype, Reflection, Presentation. Use 4 levels. Vietnamese.', 'uses' => 0, 'tags' => [['name'=>'CIEC','cat'=>'subject']]],
    ['title' => 'Real-world Problem Mapping Activity', 'description' => 'Hoạt động lập bản đồ vấn đề thực tế.', 'preview' => 'Design a classroom activity where students map a real-world problem in their community. Include steps, guiding questions, visual tools (mind map / stakeholder map), and share-out structure.', 'uses' => 0, 'tags' => [['name'=>'CIEC','cat'=>'subject']]],
    ['title' => 'Rapid Ideation Techniques for Classroom', 'description' => 'Các kỹ thuật ideation nhanh.', 'preview' => 'List and briefly explain 6 rapid ideation techniques suitable for secondary classroom (15–20 minutes each). Include how to run them and tips for facilitation.', 'uses' => 0, 'tags' => [['name'=>'CIEC','cat'=>'subject']]],
    ['title' => 'User Testing Feedback Form', 'description' => 'Mẫu thu thập phản hồi khi test sản phẩm.', 'preview' => 'Create a simple user testing feedback form for student prototypes. Include observation notes, user quotes, rating scales, and improvement suggestions. Student-friendly language.', 'uses' => 0, 'tags' => [['name'=>'STEAM','cat'=>'subject']]],
    ['title' => 'Sustainability Impact Calculator Prompt', 'description' => 'Ước tính tác động bền vững của dự án.', 'preview' => 'Help students estimate the potential sustainability impact of their project. Provide guiding questions on environmental, social, and economic impact, and a simple calculation framework.', 'uses' => 0, 'tags' => [['name'=>'STEAM','cat'=>'subject']]],
    ['title' => 'Coding + Art Integration Ideas', 'description' => 'Ý tưởng kết hợp coding và nghệ thuật.', 'preview' => 'Suggest 5 project ideas that integrate coding (Scratch / Python / micro:bit) with visual or performing arts for secondary students. Include learning goals and difficulty level.', 'uses' => 0, 'tags' => [['name'=>'STEAM','cat'=>'subject']]],
    ['title' => '3D Printing Project Scaffold', 'description' => 'Khung hỗ trợ dự án in 3D.', 'preview' => 'Create a scaffolded guide for students doing their first 3D printing project. Stages: Idea → Sketch → Digital design → Print preparation → Reflection. Include common pitfalls.', 'uses' => 0, 'tags' => [['name'=>'STEAM','cat'=>'subject']]],
    ['title' => 'Robotics Challenge Scenario', 'description' => 'Kịch bản thử thách robot.', 'preview' => 'Design a robotics challenge scenario for [GRADE] using [PLATFORM, e.g. mBot / LEGO]. Include mission, constraints, scoring rubric, and extension tasks.', 'uses' => 0, 'tags' => [['name'=>'STEAM','cat'=>'subject']]],
    ['title' => 'Design Journal Entry Prompts', 'description' => 'Câu hỏi viết nhật ký thiết kế.', 'preview' => 'Generate 10 design journal prompts that encourage deep reflection during an innovation project. Cover empathy, ideation, prototyping, testing, and personal growth.', 'uses' => 0, 'tags' => [['name'=>'CIEC','cat'=>'subject']]],
    ['title' => 'Stakeholder Analysis for Student Projects', 'description' => 'Phân tích các bên liên quan.', 'preview' => 'Guide students through a stakeholder analysis for their project. Provide template and questions to identify who is affected, their needs, and how to involve them.', 'uses' => 0, 'tags' => [['name'=>'CIEC','cat'=>'subject']]],
    ['title' => 'Pitch Practice Feedback Rubric', 'description' => 'Rubric góp ý khi luyện pitch.', 'preview' => 'Create a peer feedback rubric for student pitch practice. Criteria: Clarity of problem, Solution strength, Delivery, Visuals, Time management. 3–4 levels.', 'uses' => 0, 'tags' => [['name'=>'CIEC','cat'=>'subject']]],
    ['title' => 'Innovation Exhibition Booth Design', 'description' => 'Gợi ý thiết kế gian hàng triển lãm.', 'preview' => 'Suggest layout and content ideas for a student innovation exhibition booth. Include must-have elements, storytelling tips, and engagement activities for visitors.', 'uses' => 0, 'tags' => [['name'=>'CIEC','cat'=>'subject']]],
    ['title' => 'Mentorship Matching Questions', 'description' => 'Câu hỏi ghép mentor – học sinh.', 'preview' => 'Create questions to help match student innovation teams with suitable mentors (teachers / external experts). Focus on project needs, mentor expertise, and working style.', 'uses' => 0, 'tags' => [['name'=>'CIEC','cat'=>'subject']]],
    ['title' => 'IP & Ethics Discussion Guide', 'description' => 'Hướng dẫn thảo luận về sở hữu trí tuệ và đạo đức.', 'preview' => 'Design a 20–30 minute discussion guide for secondary students on intellectual property and ethical issues in innovation. Include scenarios and reflection questions.', 'uses' => 0, 'tags' => [['name'=>'CIEC','cat'=>'subject']]],
    ['title' => 'Iteration Log Template', 'description' => 'Mẫu ghi chép quá trình cải tiến.', 'preview' => 'Create a simple iteration log template for students to document changes to their prototype. Columns: Version, What changed, Why, Result, Next step.', 'uses' => 0, 'tags' => [['name'=>'STEAM','cat'=>'subject']]],
    ['title' => 'Community Needs Assessment Survey', 'description' => 'Khảo sát nhu cầu cộng đồng.', 'preview' => 'Help students design a short community needs assessment survey (8–10 questions) related to [TOPIC]. Include question types and tips for collecting responses ethically.', 'uses' => 0, 'tags' => [['name'=>'CIEC','cat'=>'subject']]],
    ['title' => 'STEAM Career Pathway Exploration', 'description' => 'Khám phá nghề nghiệp STEAM.', 'preview' => 'Create an activity that helps students explore STEAM career pathways connected to their current project. Include research questions, interview suggestions, and reflection.', 'uses' => 0, 'tags' => [['name'=>'STEAM','cat'=>'subject']]],
    ['title' => 'Low-cost Sensor Project Ideas', 'description' => 'Ý tưởng dự án dùng cảm biến giá rẻ.', 'preview' => 'Suggest 5 project ideas using low-cost sensors (Arduino / micro:bit / smartphone) that secondary students can build. Include learning goals and real-world application.', 'uses' => 0, 'tags' => [['name'=>'STEAM','cat'=>'subject']]],
    ['title' => 'Collaborative Prototyping Roles', 'description' => 'Phân vai khi làm prototype nhóm.', 'preview' => 'Define clear collaborative roles for a student prototyping team (4–5 members). Include responsibilities and rotation suggestions so everyone develops multiple skills.', 'uses' => 0, 'tags' => [['name'=>'STEAM','cat'=>'subject']]],
    ['title' => 'End-of-Project Showcase Script', 'description' => 'Kịch bản giới thiệu sản phẩm cuối dự án.', 'preview' => 'Write a sample 3-minute showcase script for students presenting their innovation project. Structure: Hook → Problem → Solution → Impact → Call to action. Provide sentence starters.', 'uses' => 0, 'tags' => [['name'=>'CIEC','cat'=>'subject']]],

    // === COUNSELING (25) ===
    ['title' => 'SEL Reflection Prompts – CASEL', 'description' => 'Prompt phản tư SEL theo 5 năng lực CASEL.', 'preview' => 'Generate SEL reflection prompts for [GRADE] aligned to CASEL: self-awareness, self-management, social awareness, relationship skills, responsible decision-making. Provide 3 prompts per competency. Suitable for journal or circle time. Write in Vietnamese.', 'uses' => 45, 'tags' => [['name'=>'Counseling','cat'=>'subject'],['name'=>'Popular','cat'=>'status']]],
    ['title' => 'Individual Counseling Session Structure', 'description' => 'Khung buổi tư vấn cá nhân 30–40 phút.', 'preview' => 'Create a structured individual counseling session plan (30–40 minutes) for secondary students. Include: Opening & rapport building, Exploration questions, Goal setting, Coping strategies introduction, Closing & follow-up. Provide sample scripts in Vietnamese.', 'uses' => 0, 'tags' => [['name'=>'Counseling','cat'=>'subject'],['name'=>'New','cat'=>'status']]],
    ['title' => 'Group Counseling Theme Series', 'description' => 'Chuỗi chủ đề tư vấn nhóm.', 'preview' => 'Design a 6-session group counseling series for secondary students on the theme [THEME, e.g. exam stress / friendship / self-esteem]. For each session provide: objective, key activity, discussion questions, closing.', 'uses' => 0, 'tags' => [['name'=>'Counseling','cat'=>'subject']]],
    ['title' => 'Parent Consultation Script – Emotional Support', 'description' => 'Kịch bản trao đổi với phụ huynh về hỗ trợ cảm xúc.', 'preview' => 'Write an empathetic consultation script for counselors talking with parents about a student’s emotional or behavioral concerns. Include opening, sharing observations, collaborative planning, and closing. Vietnamese.', 'uses' => 0, 'tags' => [['name'=>'Counseling','cat'=>'subject']]],
    ['title' => 'Peer Mediation Role-play Scenarios', 'description' => 'Tình huống đóng vai hòa giải bạn bè.', 'preview' => 'Create 5 realistic peer mediation role-play scenarios suitable for secondary students. Include background, conflict description, and debrief questions.', 'uses' => 0, 'tags' => [['name'=>'Counseling','cat'=>'subject']]],
    ['title' => 'Mental Health First Aid Response Guide', 'description' => 'Hướng dẫn sơ cấp cứu tâm lý.', 'preview' => 'Create a simple mental health first aid response guide for teachers and counselors when a student shows signs of distress. Include do\'s, don\'ts, and when to refer.', 'uses' => 0, 'tags' => [['name'=>'Counseling','cat'=>'subject']]],
    ['title' => 'Student Strengths Inventory Questions', 'description' => 'Câu hỏi khám phá điểm mạnh học sinh.', 'preview' => 'Generate 12 strengths-based questions to help secondary students identify their personal strengths, values, and interests. Suitable for individual or group use.', 'uses' => 0, 'tags' => [['name'=>'Counseling','cat'=>'subject']]],
    ['title' => 'Transition Support (Grade 6 & 10)', 'description' => 'Hỗ trợ chuyển cấp.', 'preview' => 'Design support activities and conversation guides for students transitioning into grade 6 or grade 10. Address common worries, new expectations, and building belonging.', 'uses' => 0, 'tags' => [['name'=>'Counseling','cat'=>'subject']]],
    ['title' => 'Career Interest Exploration Activities', 'description' => 'Hoạt động khám phá hướng nghiệp.', 'preview' => 'Create 4 short career interest exploration activities for secondary students. Include self-reflection, research, and sharing components.', 'uses' => 0, 'tags' => [['name'=>'Counseling','cat'=>'subject']]],
    ['title' => 'Bullying Incident Response Protocol', 'description' => 'Quy trình ứng phó bắt nạt.', 'preview' => 'Outline a clear step-by-step response protocol for counselors when handling a bullying incident. Include student safety, documentation, parent contact, and follow-up.', 'uses' => 0, 'tags' => [['name'=>'Counseling','cat'=>'subject']]],
    ['title' => 'Mindfulness Script for Homeroom', 'description' => 'Script mindfulness 5–7 phút.', 'preview' => 'Write a short mindfulness script (5–7 minutes) suitable for secondary homeroom. Calm language, simple breathing and body awareness. Vietnamese.', 'uses' => 0, 'tags' => [['name'=>'Counseling','cat'=>'subject']]],
    ['title' => 'Grief & Loss Support Conversation', 'description' => 'Hỗ trợ học sinh mất mát.', 'preview' => 'Provide guidance and sample phrases for counselors supporting a student experiencing grief or loss. Include what to say, what to avoid, and when to involve parents/professionals.', 'uses' => 0, 'tags' => [['name'=>'Counseling','cat'=>'subject']]],
    ['title' => 'Study Skills Coaching Dialogue', 'description' => 'Đối thoại coaching kỹ năng học tập.', 'preview' => 'Create a coaching dialogue structure to help students improve study skills. Include assessment of current habits, goal setting, strategy introduction, and accountability.', 'uses' => 0, 'tags' => [['name'=>'Counseling','cat'=>'subject']]],
    ['title' => 'Self-compassion Journal Prompts', 'description' => 'Câu hỏi nhật ký tự thương yêu.', 'preview' => 'Generate 10 self-compassion journal prompts for secondary students. Focus on kindness to self, common humanity, and mindfulness.', 'uses' => 0, 'tags' => [['name'=>'Counseling','cat'=>'subject']]],
    ['title' => 'Conflict Resolution Steps for Students', 'description' => 'Các bước giải quyết xung đột.', 'preview' => 'Create a simple 5-step conflict resolution guide that students can use independently or with peer mediators. Include example language.', 'uses' => 0, 'tags' => [['name'=>'Counseling','cat'=>'subject']]],
    ['title' => 'Emotional Regulation Toolkit', 'description' => 'Bộ công cụ điều hòa cảm xúc.', 'preview' => 'Compile an emotional regulation toolkit for secondary students. Include 8–10 practical strategies (breathing, grounding, reframing, etc.) with short how-to instructions.', 'uses' => 0, 'tags' => [['name'=>'Counseling','cat'=>'subject']]],
    ['title' => 'Referral Letter Template to External Services', 'description' => 'Mẫu thư giới thiệu dịch vụ bên ngoài.', 'preview' => 'Draft a professional referral letter template from school counselor to external mental health or support services. Include necessary information while respecting privacy.', 'uses' => 0, 'tags' => [['name'=>'Counseling','cat'=>'subject']]],
    ['title' => 'Classroom Climate Check-in Questions', 'description' => 'Câu hỏi kiểm tra không khí lớp.', 'preview' => 'Generate 10 quick classroom climate check-in questions that teachers or counselors can use at the start or end of class.', 'uses' => 0, 'tags' => [['name'=>'Counseling','cat'=>'subject']]],
    ['title' => 'Identity & Belonging Circle Prompts', 'description' => 'Câu hỏi vòng tròn bản sắc và thuộc về.', 'preview' => 'Create a set of circle prompts that help secondary students explore identity and sense of belonging in a safe way.', 'uses' => 0, 'tags' => [['name'=>'Counseling','cat'=>'subject']]],
    ['title' => 'Digital Wellness Discussion Guide', 'description' => 'Hướng dẫn thảo luận sức khỏe số.', 'preview' => 'Design a discussion guide on digital wellness for secondary students. Cover screen time, social media pressure, online relationships, and healthy habits.', 'uses' => 0, 'tags' => [['name'=>'Counseling','cat'=>'subject']]],
    ['title' => 'Motivation Rebuilding Conversation', 'description' => 'Đối thoại khôi phục động lực.', 'preview' => 'Provide a conversation framework for counselors helping students who have lost motivation. Include exploring barriers, reconnecting with values, and small next steps.', 'uses' => 0, 'tags' => [['name'=>'Counseling','cat'=>'subject']]],
    ['title' => 'Post-exam Debrief Protocol', 'description' => 'Quy trình trò chuyện sau kỳ thi.', 'preview' => 'Create a short post-exam debrief protocol for counselors or homeroom teachers. Help students process results, emotions, and plan forward.', 'uses' => 0, 'tags' => [['name'=>'Counseling','cat'=>'subject']]],
    ['title' => 'Friendship Skill Building Activities', 'description' => 'Hoạt động xây dựng kỹ năng kết bạn.', 'preview' => 'Design 5 short activities that help secondary students build friendship skills (initiating, listening, boundaries, conflict).', 'uses' => 0, 'tags' => [['name'=>'Counseling','cat'=>'subject']]],
    ['title' => 'Teacher Consultation Script (Student Concern)', 'description' => 'Kịch bản tư vấn giáo viên về học sinh.', 'preview' => 'Write a consultation script for counselors meeting with teachers about a student of concern. Focus on collaborative problem-solving and support strategies.', 'uses' => 0, 'tags' => [['name'=>'Counseling','cat'=>'subject']]],
    ['title' => 'End-of-year Wellness Reflection', 'description' => 'Phản tư sức khỏe tinh thần cuối năm.', 'preview' => 'Generate a set of end-of-year wellness reflection questions for secondary students. Cover growth, challenges, support systems, and hopes for next year.', 'uses' => 0, 'tags' => [['name'=>'Counseling','cat'=>'subject']]],

    // === ENGLISH (28) ===
    ['title' => 'Differentiated Reading Comprehension Questions', 'description' => 'Câu hỏi đọc hiểu 3 mức độ.', 'preview' => 'Generate differentiated reading comprehension questions for the following text: [PASTE TEXT]. Create: 4 literal questions, 4 inferential questions, 3 evaluative / critical thinking questions. Suitable for [GRADE]. Include model answers.', 'uses' => 40, 'tags' => [['name'=>'English','cat'=>'subject'],['name'=>'Bloom','cat'=>'framework'],['name'=>'Popular','cat'=>'status']]],
    ['title' => 'Speaking Task Card Generator – IELTS Style', 'description' => 'Thẻ nói theo format IELTS.', 'preview' => 'Create 8 IELTS-style Speaking Part 2 cue cards + follow-up Part 3 questions for Vietnamese secondary students. Topics related to school life, technology, environment, culture. Provide sample band 6–7 answers.', 'uses' => 0, 'tags' => [['name'=>'English','cat'=>'subject'],['name'=>'New','cat'=>'status']]],
    ['title' => 'Grammar in Context Mini-lesson', 'description' => 'Mini-lesson ngữ pháp theo ngữ cảnh.', 'preview' => 'Design a 15–20 minute grammar mini-lesson teaching [GRAMMAR POINT] in context for grade [GRADE]. Include example sentences, guided practice, and communicative activity.', 'uses' => 0, 'tags' => [['name'=>'English','cat'=>'subject']]],
    ['title' => 'Writing Feedback Bank (Common Errors)', 'description' => 'Ngân hàng nhận xét lỗi viết thường gặp.', 'preview' => 'Create a bank of constructive feedback comments for common writing errors made by Vietnamese secondary students (articles, tenses, word form, sentence structure, cohesion). Provide correction + explanation.', 'uses' => 0, 'tags' => [['name'=>'English','cat'=>'subject']]],
    ['title' => 'Vocabulary Expansion – Academic Word List', 'description' => 'Mở rộng từ vựng academic.', 'preview' => 'Select 10 academic words suitable for grade [GRADE] related to [TOPIC]. For each word provide: definition, example sentence, collocations, and a short practice activity.', 'uses' => 0, 'tags' => [['name'=>'English','cat'=>'subject']]],
    ['title' => 'Role-play Scenarios for Real-life Communication', 'description' => 'Tình huống đóng vai giao tiếp thực tế.', 'preview' => 'Create 6 realistic role-play scenarios for secondary English learners focusing on real-life communication (school, community, future plans). Include roles and useful language.', 'uses' => 0, 'tags' => [['name'=>'English','cat'=>'subject']]],
    ['title' => 'Literature Circle Roles & Questions', 'description' => 'Vai trò và câu hỏi Literature Circle.', 'preview' => 'Design literature circle roles and corresponding discussion questions for a novel or short story suitable for grade [GRADE].', 'uses' => 0, 'tags' => [['name'=>'English','cat'=>'subject']]],
    ['title' => 'Listening Gap-fill + Discussion', 'description' => 'Bài nghe điền từ + thảo luận.', 'preview' => 'Create a listening activity based on a short authentic or semi-authentic text about [TOPIC]. Include gap-fill questions and 3 discussion questions.', 'uses' => 0, 'tags' => [['name'=>'English','cat'=>'subject']]],
    ['title' => 'Debate Motion Generator + Scaffold', 'description' => 'Đề tài tranh biện + khung hỗ trợ.', 'preview' => 'Generate 5 debate motions suitable for secondary students on [THEME]. For each motion provide scaffolding: key arguments for/against and useful language.', 'uses' => 0, 'tags' => [['name'=>'English','cat'=>'subject']]],
    ['title' => 'Creative Writing Prompt Pack', 'description' => 'Bộ prompt viết sáng tạo.', 'preview' => 'Create 8 creative writing prompts for grade [GRADE] that encourage imagination while practicing narrative or descriptive skills. Include optional constraints.', 'uses' => 0, 'tags' => [['name'=>'English','cat'=>'subject']]],
    ['title' => 'Error Correction Technique Guide', 'description' => 'Các kỹ thuật chữa lỗi.', 'preview' => 'Explain 5 different error correction techniques teachers can use in English class (with examples). Indicate when each is most appropriate.', 'uses' => 0, 'tags' => [['name'=>'English','cat'=>'subject']]],
    ['title' => 'Fluency Practice Games', 'description' => 'Trò chơi luyện fluency.', 'preview' => 'Suggest 6 short fluency-focused games or activities for secondary English learners. Include timing, grouping, and language focus.', 'uses' => 0, 'tags' => [['name'=>'English','cat'=>'subject']]],
    ['title' => 'Genre-based Writing Templates', 'description' => 'Khung viết theo thể loại.', 'preview' => 'Provide a clear writing template and language support for the genre [GENRE] suitable for grade [GRADE].', 'uses' => 0, 'tags' => [['name'=>'English','cat'=>'subject']]],
    ['title' => 'Pronunciation Focus Mini-drill', 'description' => 'Mini-drill phát âm.', 'preview' => 'Design a short pronunciation mini-drill focusing on [SOUND / FEATURE] that Vietnamese learners often struggle with. Include minimal pairs and practice sentences.', 'uses' => 0, 'tags' => [['name'=>'English','cat'=>'subject']]],
    ['title' => 'Cross-cultural Comparison Tasks', 'description' => 'Nhiệm vụ so sánh văn hóa.', 'preview' => 'Create 4 cross-cultural comparison tasks that help students discuss Vietnamese culture and another culture in English.', 'uses' => 0, 'tags' => [['name'=>'English','cat'=>'subject']]],
    ['title' => 'Project-based Language Assessment', 'description' => 'Đánh giá ngôn ngữ theo dự án.', 'preview' => 'Design a project-based assessment for an English unit on [TOPIC]. Include task description, language criteria, and rubric.', 'uses' => 0, 'tags' => [['name'=>'English','cat'=>'subject']]],
    ['title' => 'Peer Feedback Rubric for Speaking', 'description' => 'Rubric góp ý nói cho bạn.', 'preview' => 'Create a simple peer feedback rubric for speaking activities. Criteria: Content, Fluency, Accuracy, Interaction. Student-friendly language.', 'uses' => 0, 'tags' => [['name'=>'English','cat'=>'subject']]],
    ['title' => 'Reading Strategy Poster Content', 'description' => 'Nội dung poster chiến lược đọc.', 'preview' => 'Write clear, concise content for a classroom poster on reading strategies (predicting, skimming, scanning, inferring, summarizing).', 'uses' => 0, 'tags' => [['name'=>'English','cat'=>'subject']]],
    ['title' => 'Exam Writing Task 2 Scaffold', 'description' => 'Khung hỗ trợ Writing Task 2.', 'preview' => 'Provide a step-by-step scaffold for students writing an opinion or discussion essay (IELTS-style Task 2). Include paragraph structure and useful phrases.', 'uses' => 0, 'tags' => [['name'=>'English','cat'=>'subject']]],
    ['title' => 'Content-based Language Unit (Science/History)', 'description' => 'Đơn vị học ngôn ngữ gắn nội dung.', 'preview' => 'Outline a short content-based English unit linking language learning with [SUBJECT] content for grade [GRADE].', 'uses' => 0, 'tags' => [['name'=>'English','cat'=>'subject']]],
    ['title' => 'Storytelling Sequence Cards', 'description' => 'Thẻ kể chuyện theo trình tự.', 'preview' => 'Create a set of storytelling sequence prompts or card ideas that help students practice narrative tenses and sequencing language.', 'uses' => 0, 'tags' => [['name'=>'English','cat'=>'subject']]],
    ['title' => 'Collocation Practice Sets', 'description' => 'Bài luyện collocation.', 'preview' => 'Generate collocation practice sets for [TOPIC / WORD FAMILY]. Include matching, gap-fill, and productive use activities.', 'uses' => 0, 'tags' => [['name'=>'English','cat'=>'subject']]],
    ['title' => 'Formal vs Informal Register Practice', 'description' => 'Luyện ngữ vực trang trọng – thân mật.', 'preview' => 'Create exercises that help students transform informal language into formal language and vice versa, with clear examples.', 'uses' => 0, 'tags' => [['name'=>'English','cat'=>'subject']]],
    ['title' => 'Multimedia Response Tasks', 'description' => 'Nhiệm vụ phản hồi đa phương tiện.', 'preview' => 'Design 4 multimedia response tasks where students react to a video, image, or podcast in English (speaking or writing).', 'uses' => 0, 'tags' => [['name'=>'English','cat'=>'subject']]],
    ['title' => 'Self-assessment Checklist for Writing', 'description' => 'Checklist tự đánh giá bài viết.', 'preview' => 'Create a student-friendly self-assessment checklist for writing that covers organization, language, and task achievement.', 'uses' => 0, 'tags' => [['name'=>'English','cat'=>'subject']]],
    ['title' => 'Interactive Grammar Discovery', 'description' => 'Khám phá ngữ pháp tương tác.', 'preview' => 'Design an inductive grammar discovery activity for [GRAMMAR POINT]. Students notice patterns from examples before the rule is given.', 'uses' => 0, 'tags' => [['name'=>'English','cat'=>'subject']]],
    ['title' => 'Book Club Discussion Guide', 'description' => 'Hướng dẫn thảo luận book club.', 'preview' => 'Create a discussion guide for a student book club reading [BOOK / SHORT STORY]. Include comprehension, analysis, and personal response questions.', 'uses' => 0, 'tags' => [['name'=>'English','cat'=>'subject']]],
    ['title' => 'End-of-unit Performance Task', 'description' => 'Nhiệm vụ biểu diễn cuối unit.', 'preview' => 'Design an end-of-unit performance task that allows students to demonstrate language skills authentically related to [UNIT THEME]. Include success criteria.', 'uses' => 0, 'tags' => [['name'=>'English','cat'=>'subject']]],

    // === GENERAL (25) ===
    ['title' => 'Homeroom Activity Bank – 15 minutes', 'description' => 'Ngân hàng hoạt động chủ nhiệm 15 phút.', 'preview' => 'Generate 10 ready-to-use 15-minute homeroom activities for secondary students on the theme: [THEME]. Each activity includes objective, materials, steps, and reflection question. Suitable for Vietnamese classroom.', 'uses' => 55, 'tags' => [['name'=>'General','cat'=>'subject'],['name'=>'Popular','cat'=>'status']]],
    ['title' => 'Lesson Hook Generator – Any Subject', 'description' => 'Tạo 5 cách mở bài hấp dẫn.', 'preview' => 'Create 5 engaging lesson hooks for a [SUBJECT] lesson on [TOPIC] for grade [GRADE]. Include: Hook description, Time needed, Materials, Transition to main lesson. Focus on curiosity and relevance to Vietnamese students.', 'uses' => 0, 'tags' => [['name'=>'General','cat'=>'subject'],['name'=>'New','cat'=>'status']]],
    ['title' => 'Exit Ticket Question Bank', 'description' => 'Ngân hàng câu hỏi exit ticket.', 'preview' => 'Generate 15 varied exit ticket questions that teachers can use across subjects to check understanding, reflection, or next-step planning.', 'uses' => 0, 'tags' => [['name'=>'General','cat'=>'subject']]],
    ['title' => 'Collaborative Learning Structures', 'description' => 'Cấu trúc học hợp tác.', 'preview' => 'Describe 6 collaborative learning structures (e.g. Think-Pair-Share variations, Jigsaw, Rally Coach) with clear steps and classroom management tips.', 'uses' => 0, 'tags' => [['name'=>'General','cat'=>'subject']]],
    ['title' => 'Differentiation Strategies Quick List', 'description' => 'Danh sách chiến lược phân hóa nhanh.', 'preview' => 'Provide a quick-reference list of practical differentiation strategies for content, process, and product that secondary teachers can apply immediately.', 'uses' => 0, 'tags' => [['name'=>'General','cat'=>'subject']]],
    ['title' => 'Classroom Routine Script', 'description' => 'Script xây dựng nề nếp lớp.', 'preview' => 'Write sample teacher language and routines for starting class, transitioning, and ending class effectively in a secondary setting.', 'uses' => 0, 'tags' => [['name'=>'General','cat'=>'subject']]],
    ['title' => 'Student Goal-setting Template', 'description' => 'Mẫu đặt mục tiêu học sinh.', 'preview' => 'Create a simple, student-friendly goal-setting template that includes academic, personal, and learning habit goals, with review checkpoints.', 'uses' => 0, 'tags' => [['name'=>'General','cat'=>'subject']]],
    ['title' => 'Peer Teaching Protocol', 'description' => 'Quy trình dạy lẫn nhau.', 'preview' => 'Design a clear peer teaching protocol that students can follow when explaining concepts to each other. Include preparation and feedback steps.', 'uses' => 0, 'tags' => [['name'=>'General','cat'=>'subject']]],
    ['title' => 'Formative Assessment Techniques', 'description' => 'Các kỹ thuật đánh giá quá trình.', 'preview' => 'List and briefly explain 10 practical formative assessment techniques suitable for secondary classrooms, with examples.', 'uses' => 0, 'tags' => [['name'=>'General','cat'=>'subject']]],
    ['title' => 'Growth Mindset Language Bank', 'description' => 'Ngân hàng ngôn ngữ tư duy phát triển.', 'preview' => 'Create a bank of growth mindset phrases teachers can use when giving feedback or responding to student struggle.', 'uses' => 0, 'tags' => [['name'=>'General','cat'=>'subject']]],
    ['title' => 'Inquiry Question Stems', 'description' => 'Mẫu câu hỏi khơi gợi tìm tòi.', 'preview' => 'Provide a rich list of inquiry question stems that teachers and students can use to deepen thinking across subjects.', 'uses' => 0, 'tags' => [['name'=>'General','cat'=>'subject']]],
    ['title' => 'Reflection Protocol (What–So What–Now What)', 'description' => 'Quy trình phản tư 3 bước.', 'preview' => 'Explain and provide examples of the What – So What – Now What reflection protocol adapted for secondary students.', 'uses' => 0, 'tags' => [['name'=>'General','cat'=>'subject']]],
    ['title' => 'Classroom Agreement Co-creation', 'description' => 'Cùng xây dựng thỏa thuận lớp.', 'preview' => 'Guide teachers through a process to co-create classroom agreements with secondary students. Include facilitation steps and sample questions.', 'uses' => 0, 'tags' => [['name'=>'General','cat'=>'subject']]],
    ['title' => 'Time Management Mini-lesson', 'description' => 'Mini-lesson quản lý thời gian.', 'preview' => 'Design a short mini-lesson on time management skills for secondary students, including practical strategies and a personal planning activity.', 'uses' => 0, 'tags' => [['name'=>'General','cat'=>'subject']]],
    ['title' => 'Visual Thinking Routines', 'description' => 'Các routine tư duy trực quan.', 'preview' => 'Describe 5 visual thinking routines (e.g. See-Think-Wonder) that work well in secondary classrooms, with how to introduce them.', 'uses' => 0, 'tags' => [['name'=>'General','cat'=>'subject']]],
    ['title' => 'Student Voice Survey Questions', 'description' => 'Câu hỏi khảo sát tiếng nói học sinh.', 'preview' => 'Generate a set of student voice survey questions about learning experience, classroom environment, and suggestions for improvement.', 'uses' => 0, 'tags' => [['name'=>'General','cat'=>'subject']]],
    ['title' => 'Cross-curricular Connection Ideas', 'description' => 'Ý tưởng kết nối liên môn.', 'preview' => 'Suggest practical ways teachers of different subjects can create meaningful cross-curricular connections around a shared theme.', 'uses' => 0, 'tags' => [['name'=>'General','cat'=>'subject']]],
    ['title' => 'Homework Design Principles', 'description' => 'Nguyên tắc thiết kế bài tập về nhà.', 'preview' => 'Outline research-informed principles for designing effective homework at secondary level, with examples of good and less effective tasks.', 'uses' => 0, 'tags' => [['name'=>'General','cat'=>'subject']]],
    ['title' => 'Feedback Sentence Starters', 'description' => 'Câu mở đầu khi góp ý.', 'preview' => 'Create useful sentence starters for teachers giving written or oral feedback that is specific, kind, and actionable.', 'uses' => 0, 'tags' => [['name'=>'General','cat'=>'subject']]],
    ['title' => 'Inclusive Classroom Adjustments', 'description' => 'Điều chỉnh lớp học hòa nhập.', 'preview' => 'List practical inclusive adjustments teachers can make for diverse learners (attention, language, processing speed, anxiety) without lowering expectations.', 'uses' => 0, 'tags' => [['name'=>'General','cat'=>'subject']]],
    ['title' => 'Energy Transition Activities', 'description' => 'Hoạt động chuyển đổi năng lượng lớp.', 'preview' => 'Suggest short (2–5 minute) energy transition activities teachers can use when students need to refocus or reset.', 'uses' => 0, 'tags' => [['name'=>'General','cat'=>'subject']]],
    ['title' => 'Metacognition Prompt Pack', 'description' => 'Bộ câu hỏi siêu nhận thức.', 'preview' => 'Generate a pack of metacognitive prompts students can use before, during, and after learning tasks.', 'uses' => 0, 'tags' => [['name'=>'General','cat'=>'subject']]],
    ['title' => 'Celebration & Recognition Ideas', 'description' => 'Ý tưởng ghi nhận và ăn mừng.', 'preview' => 'Suggest meaningful, low-cost ways to celebrate student effort, growth, and contribution in a secondary school setting.', 'uses' => 0, 'tags' => [['name'=>'General','cat'=>'subject']]],
    ['title' => 'End-of-term Reflection Template', 'description' => 'Mẫu phản tư cuối học kỳ.', 'preview' => 'Create a student end-of-term reflection template covering academic progress, learning habits, challenges, and goals for next term.', 'uses' => 0, 'tags' => [['name'=>'General','cat'=>'subject']]],
    ['title' => 'Teacher Self-observation Checklist', 'description' => 'Checklist tự quan sát giờ dạy.', 'preview' => 'Design a practical self-observation checklist teachers can use after a lesson to reflect on engagement, clarity, differentiation, and classroom climate.', 'uses' => 0, 'tags' => [['name'=>'General','cat'=>'subject']]],

    // === MATH (28) ===
    ['title' => 'Real-world Math Problem Generator', 'description' => 'Bài toán thực tế gắn đời sống.', 'preview' => 'Generate 5 real-world math problems for grade [GRADE] on the topic [TOPIC]. Contexts should be relevant to Vietnamese secondary students (market, traffic, environment, technology, school events). Include solutions and extension questions.', 'uses' => 50, 'tags' => [['name'=>'Math','cat'=>'subject'],['name'=>'UBD','cat'=>'framework'],['name'=>'Popular','cat'=>'status']]],
    ['title' => 'Conceptual Understanding Check Questions', 'description' => 'Câu hỏi kiểm tra hiểu khái niệm.', 'preview' => 'Create 8 conceptual understanding questions (not procedural) for [TOPIC] at grade [GRADE]. Questions should reveal student thinking, common misconceptions, and require explanation. Provide sample student responses and teacher follow-up.', 'uses' => 0, 'tags' => [['name'=>'Math','cat'=>'subject'],['name'=>'Bloom','cat'=>'framework'],['name'=>'New','cat'=>'status']]],
    ['title' => 'Mistake Analysis Activity', 'description' => 'Hoạt động phân tích lỗi sai.', 'preview' => 'Design a mistake analysis activity for [TOPIC]. Provide 4–5 common student errors, ask students to find and explain the mistake, then correct it.', 'uses' => 0, 'tags' => [['name'=>'Math','cat'=>'subject']]],
    ['title' => 'Multiple Representations Task', 'description' => 'Nhiệm vụ đa biểu diễn.', 'preview' => 'Create a task that requires students to represent the same mathematical idea in at least 3 ways (symbolic, graphical, verbal, tabular) for [TOPIC].', 'uses' => 0, 'tags' => [['name'=>'Math','cat'=>'subject']]],
    ['title' => 'Low-floor High-ceiling Problems', 'description' => 'Bài toán sàn thấp – trần cao.', 'preview' => 'Generate 3 low-floor high-ceiling problems related to [TOPIC] that all students can access but that also challenge advanced learners.', 'uses' => 0, 'tags' => [['name'=>'Math','cat'=>'subject']]],
    ['title' => 'Math Talk Prompt Stems', 'description' => 'Câu mở đầu Math Talk.', 'preview' => 'Provide a set of Math Talk prompt stems that encourage students to explain reasoning, agree/disagree respectfully, and build on others\' ideas.', 'uses' => 0, 'tags' => [['name'=>'Math','cat'=>'subject']]],
    ['title' => 'Visual Proof Exploration', 'description' => 'Khám phá chứng minh trực quan.', 'preview' => 'Design an activity where students explore a visual proof or geometric representation of [CONCEPT]. Include guiding questions.', 'uses' => 0, 'tags' => [['name'=>'Math','cat'=>'subject']]],
    ['title' => 'Estimation & Number Sense Challenges', 'description' => 'Thử thách ước lượng và cảm số.', 'preview' => 'Create 5 estimation and number sense challenges suitable for grade [GRADE] that develop intuition before formal calculation.', 'uses' => 0, 'tags' => [['name'=>'Math','cat'=>'subject']]],
    ['title' => 'Project-based Math Unit Outline', 'description' => 'Dàn ý unit Toán theo dự án.', 'preview' => 'Outline a project-based math unit for grade [GRADE] around a real-world context. Include driving question, key math content, milestones, and final product.', 'uses' => 0, 'tags' => [['name'=>'Math','cat'=>'subject'],['name'=>'UBD','cat'=>'framework']]],
    ['title' => 'Formative Checkpoint Questions', 'description' => 'Câu hỏi kiểm tra định kỳ.', 'preview' => 'Generate a set of short formative checkpoint questions for [TOPIC] that can be used mid-unit to diagnose understanding.', 'uses' => 0, 'tags' => [['name'=>'Math','cat'=>'subject']]],
    ['title' => 'Differentiation – Support & Challenge', 'description' => 'Phân hóa hỗ trợ và thử thách.', 'preview' => 'For a standard problem on [TOPIC], create a supported version (scaffolds) and a challenge version (extension) while keeping the core learning goal.', 'uses' => 0, 'tags' => [['name'=>'Math','cat'=>'subject']]],
    ['title' => 'Math Journal Reflection Prompts', 'description' => 'Câu hỏi nhật ký Toán.', 'preview' => 'Generate 10 math journal prompts that encourage students to reflect on strategies, mistakes, and connections.', 'uses' => 0, 'tags' => [['name'=>'Math','cat'=>'subject']]],
    ['title' => 'Real Data Investigation', 'description' => 'Điều tra dữ liệu thực.', 'preview' => 'Design a short investigation using real or realistic data related to [CONTEXT] that requires students to apply [MATH SKILL].', 'uses' => 0, 'tags' => [['name'=>'Math','cat'=>'subject']]],
    ['title' => 'Strategy Comparison Tasks', 'description' => 'So sánh các chiến lược giải.', 'preview' => 'Create a task where students solve the same problem using two different strategies and then compare efficiency and understanding.', 'uses' => 0, 'tags' => [['name'=>'Math','cat'=>'subject']]],
    ['title' => 'Vocabulary in Context Cards', 'description' => 'Thẻ từ vựng Toán theo ngữ cảnh.', 'preview' => 'Create vocabulary cards for key terms in [TOPIC]. Each card includes definition, example, non-example, and a sentence using the term.', 'uses' => 0, 'tags' => [['name'=>'Math','cat'=>'subject']]],
    ['title' => 'Collaborative Problem-solving Roles', 'description' => 'Vai trò khi giải toán nhóm.', 'preview' => 'Define collaborative roles for group problem-solving in math (e.g. Facilitator, Recorder, Questioner, Summarizer) with clear responsibilities.', 'uses' => 0, 'tags' => [['name'=>'Math','cat'=>'subject']]],
    ['title' => 'Diagnostic Pre-assessment', 'description' => 'Đánh giá chẩn đoán đầu unit.', 'preview' => 'Create a short diagnostic pre-assessment for [TOPIC] that reveals prerequisite knowledge and common gaps.', 'uses' => 0, 'tags' => [['name'=>'Math','cat'=>'subject']]],
    ['title' => 'Extension for Advanced Learners', 'description' => 'Bài mở rộng cho học sinh khá giỏi.', 'preview' => 'Design 3 extension tasks for advanced students who have mastered the core content of [TOPIC].', 'uses' => 0, 'tags' => [['name'=>'Math','cat'=>'subject']]],
    ['title' => 'Connection to Other Subjects', 'description' => 'Kết nối Toán với môn khác.', 'preview' => 'Suggest meaningful connections between [MATH TOPIC] and other subjects (Science, Geography, Art, Economics) with example activities.', 'uses' => 0, 'tags' => [['name'=>'Math','cat'=>'subject']]],
    ['title' => 'Exam-style Question with Rubric', 'description' => 'Câu hỏi dạng đề + rubric.', 'preview' => 'Create an exam-style question on [TOPIC] for grade [GRADE] and provide a detailed scoring rubric.', 'uses' => 0, 'tags' => [['name'=>'Math','cat'=>'subject']]],
    ['title' => 'Growth Tracking Reflection', 'description' => 'Phản tư theo dõi sự tiến bộ.', 'preview' => 'Create reflection questions that help students track their growth in mathematical understanding and confidence over a unit.', 'uses' => 0, 'tags' => [['name'=>'Math','cat'=>'subject']]],
    ['title' => 'Interactive Digital Task Ideas', 'description' => 'Ý tưởng nhiệm vụ số.', 'preview' => 'Suggest interactive digital task ideas (using free tools) that deepen understanding of [TOPIC].', 'uses' => 0, 'tags' => [['name'=>'Math','cat'=>'subject']]],
    ['title' => 'Common Error Spotting', 'description' => 'Phát hiện lỗi phổ biến.', 'preview' => 'List common errors students make with [TOPIC] and design a short activity where students spot and correct them.', 'uses' => 0, 'tags' => [['name'=>'Math','cat'=>'subject']]],
    ['title' => 'Open-middle Problems', 'description' => 'Bài toán open-middle.', 'preview' => 'Create 3 open-middle problems related to [TOPIC] that have multiple solution paths but a specific constraint or answer range.', 'uses' => 0, 'tags' => [['name'=>'Math','cat'=>'subject']]],
    ['title' => 'Math + Coding Mini-project', 'description' => 'Mini-project Toán kết hợp coding.', 'preview' => 'Design a short mini-project that combines [MATH CONCEPT] with basic coding (Scratch or Python) for secondary students.', 'uses' => 0, 'tags' => [['name'=>'Math','cat'=>'subject']]],
    ['title' => 'Peer Explanation Protocol', 'description' => 'Quy trình giải thích cho bạn.', 'preview' => 'Create a simple protocol for students to explain their mathematical thinking to a peer, including listening and questioning roles.', 'uses' => 0, 'tags' => [['name'=>'Math','cat'=>'subject']]],
    ['title' => 'End-of-unit Performance Task', 'description' => 'Nhiệm vụ biểu diễn cuối unit.', 'preview' => 'Design a performance task that assesses deep understanding of [TOPIC] through application or explanation rather than only calculation.', 'uses' => 0, 'tags' => [['name'=>'Math','cat'=>'subject']]],
    ['title' => 'Teacher Questioning Sequence', 'description' => 'Chuỗi câu hỏi của giáo viên.', 'preview' => 'Generate a sequence of teacher questions that progressively deepen student thinking on [CONCEPT], from basic recall to justification and extension.', 'uses' => 0, 'tags' => [['name'=>'Math','cat'=>'subject']]],

    // === SCIENCE (28) ===
    ['title' => 'Inquiry-based Lab Investigation Design', 'description' => 'Thiết kế thí nghiệm theo hướng inquiry.', 'preview' => 'Design an inquiry-based science investigation for grade [GRADE] on [TOPIC]. Include: Guiding question, Materials (school-available), Variables, Procedure scaffold, Data table template, Analysis & conclusion questions, Safety notes. Align with Vietnamese secondary science curriculum.', 'uses' => 0, 'tags' => [['name'=>'Science','cat'=>'subject'],['name'=>'UBD','cat'=>'framework'],['name'=>'New','cat'=>'status']]],
    ['title' => 'Science Misconception Probe Questions', 'description' => 'Câu hỏi phát hiện quan niệm sai.', 'preview' => 'Generate 6 misconception probe questions for [TOPIC] at secondary level. For each question provide: Common incorrect answer, Correct scientific explanation, Follow-up discussion prompt. Write in accessible Vietnamese.', 'uses' => 48, 'tags' => [['name'=>'Science','cat'=>'subject'],['name'=>'Popular','cat'=>'status']]],
    ['title' => 'CER (Claim-Evidence-Reasoning) Scaffold', 'description' => 'Khung Claim-Evidence-Reasoning.', 'preview' => 'Create a student-friendly CER scaffold with sentence starters and examples for a science investigation on [TOPIC].', 'uses' => 0, 'tags' => [['name'=>'Science','cat'=>'subject']]],
    ['title' => 'Phenomena-based Lesson Hook', 'description' => 'Mở bài dựa trên hiện tượng.', 'preview' => 'Design a phenomena-based lesson hook for [TOPIC] that sparks curiosity. Include the phenomenon description, student observation prompts, and transition to investigation.', 'uses' => 0, 'tags' => [['name'=>'Science','cat'=>'subject']]],
    ['title' => 'Lab Safety Scenario Discussion', 'description' => 'Thảo luận tình huống an toàn phòng thí nghiệm.', 'preview' => 'Create 5 realistic lab safety scenarios for secondary students. For each, ask students what could go wrong and how to respond.', 'uses' => 0, 'tags' => [['name'=>'Science','cat'=>'subject']]],
    ['title' => 'Data Analysis & Graph Interpretation', 'description' => 'Phân tích dữ liệu và đọc đồ thị.', 'preview' => 'Provide a data set related to [TOPIC] and design questions that require students to interpret graphs, identify trends, and draw conclusions.', 'uses' => 0, 'tags' => [['name'=>'Science','cat'=>'subject']]],
    ['title' => 'Cross-cutting Concepts Integration', 'description' => 'Tích hợp khái niệm xuyên suốt.', 'preview' => 'Show how the cross-cutting concept [CONCEPT, e.g. Cause & Effect / Systems] can be explicitly taught and assessed within a unit on [TOPIC].', 'uses' => 0, 'tags' => [['name'=>'Science','cat'=>'subject']]],
    ['title' => 'Science Notebook Entry Prompts', 'description' => 'Câu hỏi viết sổ tay khoa học.', 'preview' => 'Generate science notebook entry prompts that encourage careful observation, questioning, and reflection during a unit on [TOPIC].', 'uses' => 0, 'tags' => [['name'=>'Science','cat'=>'subject']]],
    ['title' => 'Model Building Activity', 'description' => 'Hoạt động xây dựng mô hình.', 'preview' => 'Design a model-building activity for [CONCEPT]. Include purpose, materials, constraints, and questions that push students to evaluate the model\'s strengths and limitations.', 'uses' => 0, 'tags' => [['name'=>'Science','cat'=>'subject']]],
    ['title' => 'Argumentation from Evidence', 'description' => 'Lập luận dựa trên bằng chứng.', 'preview' => 'Create a structured argumentation activity where students use evidence to support or refute a scientific claim related to [TOPIC].', 'uses' => 0, 'tags' => [['name'=>'Science','cat'=>'subject']]],
    ['title' => 'Real-world Application Case Study', 'description' => 'Case study ứng dụng thực tế.', 'preview' => 'Write a short real-world case study that requires students to apply knowledge of [TOPIC] to analyze a situation or propose solutions.', 'uses' => 0, 'tags' => [['name'=>'Science','cat'=>'subject']]],
    ['title' => 'Differentiation in Lab Groups', 'description' => 'Phân hóa trong nhóm thí nghiệm.', 'preview' => 'Suggest practical ways to differentiate roles, scaffolding, and challenge within lab groups so all students are productively engaged.', 'uses' => 0, 'tags' => [['name'=>'Science','cat'=>'subject']]],
    ['title' => 'Formative Check – Exit Ticket Science', 'description' => 'Exit ticket khoa học.', 'preview' => 'Create 5 varied exit ticket questions for a science lesson on [TOPIC] that check conceptual understanding.', 'uses' => 0, 'tags' => [['name'=>'Science','cat'=>'subject']]],
    ['title' => 'STEM Career Connection', 'description' => 'Kết nối nghề nghiệp STEM.', 'preview' => 'Design a short activity that connects the current science topic to relevant STEM careers, including research or interview components.', 'uses' => 0, 'tags' => [['name'=>'Science','cat'=>'subject']]],
    ['title' => 'Environmental Issue Investigation', 'description' => 'Điều tra vấn đề môi trường.', 'preview' => 'Create an investigation outline where students examine a local or global environmental issue through the lens of [SCIENCE TOPIC].', 'uses' => 0, 'tags' => [['name'=>'Science','cat'=>'subject']]],
    ['title' => 'Experimental Design Critique', 'description' => 'Phê bình thiết kế thí nghiệm.', 'preview' => 'Provide a flawed experimental design related to [TOPIC] and ask students to critique and improve it.', 'uses' => 0, 'tags' => [['name'=>'Science','cat'=>'subject']]],
    ['title' => 'Vocabulary Concept Map', 'description' => 'Sơ đồ khái niệm từ vựng.', 'preview' => 'Guide students to create a concept map for key vocabulary in [TOPIC], showing relationships between terms.', 'uses' => 0, 'tags' => [['name'=>'Science','cat'=>'subject']]],
    ['title' => 'Collaborative Sense-making Protocol', 'description' => 'Quy trình cùng kiến tạo hiểu biết.', 'preview' => 'Design a collaborative sense-making protocol students can use after collecting data or observing a phenomenon.', 'uses' => 0, 'tags' => [['name'=>'Science','cat'=>'subject']]],
    ['title' => 'Assessment Rubric for Investigation', 'description' => 'Rubric đánh giá bài điều tra.', 'preview' => 'Create a rubric for assessing student science investigations, covering question, method, data, analysis, and communication.', 'uses' => 0, 'tags' => [['name'=>'Science','cat'=>'subject']]],
    ['title' => 'Simulation Follow-up Questions', 'description' => 'Câu hỏi sau khi dùng mô phỏng.', 'preview' => 'Generate thoughtful follow-up questions after students use a simulation related to [TOPIC] to deepen conceptual understanding.', 'uses' => 0, 'tags' => [['name'=>'Science','cat'=>'subject']]],
    ['title' => 'Historical Science Story Integration', 'description' => 'Tích hợp câu chuyện lịch sử khoa học.', 'preview' => 'Suggest how to integrate a short historical science story or scientist biography into a lesson on [TOPIC] to humanize the content.', 'uses' => 0, 'tags' => [['name'=>'Science','cat'=>'subject']]],
    ['title' => 'Student-led Demonstration Guide', 'description' => 'Hướng dẫn học sinh thuyết trình thí nghiệm.', 'preview' => 'Create a guide that helps students prepare and deliver a short science demonstration or explanation to peers.', 'uses' => 0, 'tags' => [['name'=>'Science','cat'=>'subject']]],
    ['title' => 'Reflection on Scientific Practices', 'description' => 'Phản tư về thực hành khoa học.', 'preview' => 'Generate reflection questions that help students think about how they used scientific practices (questioning, modeling, arguing, etc.) during a unit.', 'uses' => 0, 'tags' => [['name'=>'Science','cat'=>'subject']]],
    ['title' => 'Interdisciplinary Science + Math', 'description' => 'Liên môn Khoa học – Toán.', 'preview' => 'Design an activity that meaningfully integrates science content [TOPIC] with mathematical skills (graphing, proportional reasoning, etc.).', 'uses' => 0, 'tags' => [['name'=>'Science','cat'=>'subject']]],
    ['title' => 'Project Exhibition Criteria', 'description' => 'Tiêu chí triển lãm dự án.', 'preview' => 'Create clear exhibition criteria and visitor interaction ideas for a student science project showcase.', 'uses' => 0, 'tags' => [['name'=>'Science','cat'=>'subject']]],
    ['title' => 'Hypothesis Refinement Practice', 'description' => 'Luyện cải tiến giả thuyết.', 'preview' => 'Provide practice scenarios where students refine weak or untestable hypotheses into strong, testable ones.', 'uses' => 0, 'tags' => [['name'=>'Science','cat'=>'subject']]],
    ['title' => 'Observation vs Inference Activity', 'description' => 'Phân biệt quan sát và suy luận.', 'preview' => 'Design an activity that helps students clearly distinguish between observation and inference using a science context.', 'uses' => 0, 'tags' => [['name'=>'Science','cat'=>'subject']]],
    ['title' => 'End-of-unit Conceptual Test', 'description' => 'Bài kiểm tra khái niệm cuối unit.', 'preview' => 'Create a short conceptual test (not pure recall) for [TOPIC] that reveals depth of understanding and remaining misconceptions.', 'uses' => 0, 'tags' => [['name'=>'Science','cat'=>'subject']]],

    // === VIETNAMESE (28) ===
    ['title' => 'Phân tích văn bản theo 3 mức độ', 'description' => 'Câu hỏi phân tích văn bản 3 tầng.', 'preview' => 'Tạo bộ câu hỏi phân tích văn bản cho tác phẩm [TÊN TÁC PHẨM] lớp [KHỐI]. Gồm: 4 câu hỏi nhận biết, 4 câu hỏi thông hiểu, 3 câu hỏi vận dụng / đánh giá. Kèm đáp án gợi ý và yêu cầu kỹ năng nghị luận.', 'uses' => 52, 'tags' => [['name'=>'Vietnamese','cat'=>'subject'],['name'=>'Bloom','cat'=>'framework'],['name'=>'Popular','cat'=>'status']]],
    ['title' => 'Bài tập viết đoạn văn nghị luận', 'description' => 'Đề bài và khung viết đoạn nghị luận.', 'preview' => 'Tạo 5 đề bài viết đoạn văn nghị luận (150–200 chữ) cho học sinh lớp [KHỐI] theo chủ đề [CHỦ ĐỀ]. Mỗi đề kèm: Định hướng ý, Cấu trúc đoạn gợi ý, Tiêu chí đánh giá ngắn. Phù hợp chương trình Ngữ văn THCS/THPT.', 'uses' => 0, 'tags' => [['name'=>'Vietnamese','cat'=>'subject'],['name'=>'New','cat'=>'status']]],
    ['title' => 'So sánh hai tác phẩm văn học', 'description' => 'Câu hỏi so sánh tác phẩm.', 'preview' => 'Thiết kế bộ câu hỏi và khung so sánh hai tác phẩm [TÁC PHẨM 1] và [TÁC PHẨM 2] theo các tiêu chí: chủ đề, nhân vật, nghệ thuật, thông điệp. Phù hợp lớp [KHỐI].', 'uses' => 0, 'tags' => [['name'=>'Vietnamese','cat'=>'subject']]],
    ['title' => 'Kỹ năng đọc hiểu văn bản thông tin', 'description' => 'Luyện đọc văn bản thông tin.', 'preview' => 'Tạo bài luyện đọc hiểu văn bản thông tin (báo chí / khoa học phổ thông) cho lớp [KHỐI]. Gồm đoạn văn bản ngắn, câu hỏi nhận biết – thông hiểu – vận dụng, và hướng dẫn chiến lược đọc.', 'uses' => 0, 'tags' => [['name'=>'Vietnamese','cat'=>'subject']]],
    ['title' => 'Luyện từ và câu theo ngữ cảnh', 'description' => 'Bài tập từ và câu.', 'preview' => 'Thiết kế bài tập luyện từ và câu gắn với ngữ cảnh văn bản [TÊN VĂN BẢN / CHỦ ĐỀ]. Tập trung vào từ đồng nghĩa, trái nghĩa, biện pháp tu từ và cách diễn đạt.', 'uses' => 0, 'tags' => [['name'=>'Vietnamese','cat'=>'subject']]],
    ['title' => 'Viết thư / đơn / báo cáo', 'description' => 'Luyện viết văn bản hành chính.', 'preview' => 'Tạo đề bài và khung hướng dẫn viết [THƯ / ĐƠN / BÁO CÁO] cho học sinh lớp [KHỐI]. Kèm mẫu ngôn ngữ trang trọng và tiêu chí đánh giá.', 'uses' => 0, 'tags' => [['name'=>'Vietnamese','cat'=>'subject']]],
    ['title' => 'Phân tích nhân vật theo tiêu chí', 'description' => 'Phân tích nhân vật.', 'preview' => 'Cung cấp khung phân tích nhân vật trong tác phẩm [TÊN TÁC PHẨM] với các tiêu chí: ngoại hình, tính cách, hành động, quan hệ, ý nghĩa. Kèm câu hỏi gợi mở.', 'uses' => 0, 'tags' => [['name'=>'Vietnamese','cat'=>'subject']]],
    ['title' => 'Thảo luận nhóm về giá trị sống', 'description' => 'Thảo luận giá trị sống từ văn học.', 'preview' => 'Thiết kế hoạt động thảo luận nhóm dựa trên tác phẩm [TÊN TÁC PHẨM] xoay quanh giá trị sống / thông điệp. Gồm câu hỏi định hướng và quy tắc thảo luận.', 'uses' => 0, 'tags' => [['name'=>'Vietnamese','cat'=>'subject']]],
    ['title' => 'Tóm tắt nội dung theo sơ đồ', 'description' => 'Tóm tắt bằng sơ đồ.', 'preview' => 'Hướng dẫn học sinh tóm tắt nội dung tác phẩm / đoạn văn bằng sơ đồ (mind map, flowchart, bảng). Cung cấp mẫu và tiêu chí đánh giá.', 'uses' => 0, 'tags' => [['name'=>'Vietnamese','cat'=>'subject']]],
    ['title' => 'Viết đoạn văn miêu tả / biểu cảm', 'description' => 'Luyện viết miêu tả – biểu cảm.', 'preview' => 'Tạo đề bài viết đoạn văn miêu tả hoặc biểu cảm cho lớp [KHỐI]. Kèm gợi ý về giác quan, hình ảnh, cảm xúc và khung cấu trúc đoạn.', 'uses' => 0, 'tags' => [['name'=>'Vietnamese','cat'=>'subject']]],
    ['title' => 'Phát hiện biện pháp tu từ', 'description' => 'Nhận diện và phân tích biện pháp tu từ.', 'preview' => 'Thiết kế bài tập nhận diện và phân tích tác dụng của các biện pháp tu từ trong đoạn văn / bài thơ [TÊN]. Kèm đáp án giải thích.', 'uses' => 0, 'tags' => [['name'=>'Vietnamese','cat'=>'subject']]],
    ['title' => 'Liên hệ thực tế với tác phẩm', 'description' => 'Liên hệ văn học với đời sống.', 'preview' => 'Tạo câu hỏi và hoạt động giúp học sinh liên hệ nội dung / thông điệp của tác phẩm [TÊN] với thực tế cuộc sống hiện nay.', 'uses' => 0, 'tags' => [['name'=>'Vietnamese','cat'=>'subject']]],
    ['title' => 'Đánh giá quan điểm trong văn bản', 'description' => 'Đánh giá quan điểm tác giả.', 'preview' => 'Thiết kế câu hỏi yêu cầu học sinh nhận diện và đánh giá quan điểm của tác giả trong văn bản nghị luận / báo chí. Kèm hướng dẫn lập luận.', 'uses' => 0, 'tags' => [['name'=>'Vietnamese','cat'=>'subject']]],
    ['title' => 'Luyện kỹ năng thuyết trình', 'description' => 'Luyện thuyết trình về văn học.', 'preview' => 'Tạo khung và tiêu chí đánh giá bài thuyết trình ngắn (3–5 phút) về một tác phẩm hoặc nhân vật văn học cho học sinh lớp [KHỐI].', 'uses' => 0, 'tags' => [['name'=>'Vietnamese','cat'=>'subject']]],
    ['title' => 'Sáng tạo kết thúc khác cho truyện', 'description' => 'Viết lại kết thúc.', 'preview' => 'Yêu cầu học sinh sáng tạo một kết thúc khác cho truyện [TÊN TRUYỆN] và giải thích lý do lựa chọn. Cung cấp gợi ý và tiêu chí đánh giá tính logic – sáng tạo.', 'uses' => 0, 'tags' => [['name'=>'Vietnamese','cat'=>'subject']]],
    ['title' => 'Phân tích ngôn ngữ báo chí', 'description' => 'Phân tích ngôn ngữ báo chí.', 'preview' => 'Thiết kế bài tập phân tích đặc điểm ngôn ngữ của một đoạn báo chí (từ ngữ, câu, giọng điệu, mục đích). Phù hợp lớp [KHỐI].', 'uses' => 0, 'tags' => [['name'=>'Vietnamese','cat'=>'subject']]],
    ['title' => 'Viết bài nghị luận có dẫn chứng', 'description' => 'Viết nghị luận có dẫn chứng.', 'preview' => 'Tạo đề bài nghị luận xã hội hoặc văn học yêu cầu sử dụng dẫn chứng. Cung cấp khung lập luận và gợi ý cách đưa dẫn chứng thuyết phục.', 'uses' => 0, 'tags' => [['name'=>'Vietnamese','cat'=>'subject']]],
    ['title' => 'Ôn tập theo chủ đề văn học', 'description' => 'Ôn tập theo chủ đề.', 'preview' => 'Thiết kế hệ thống câu hỏi ôn tập theo chủ đề [CHỦ ĐỀ VĂN HỌC] cho lớp [KHỐI], bao gồm nhận biết, thông hiểu và vận dụng.', 'uses' => 0, 'tags' => [['name'=>'Vietnamese','cat'=>'subject']]],
    ['title' => 'Câu hỏi gợi mở cho giờ học', 'description' => 'Câu hỏi gợi mở.', 'preview' => 'Tạo bộ câu hỏi gợi mở (open-ended) để khởi động và dẫn dắt giờ học về tác phẩm [TÊN TÁC PHẨM].', 'uses' => 0, 'tags' => [['name'=>'Vietnamese','cat'=>'subject']]],
    ['title' => 'Phiếu tự đánh giá kỹ năng viết', 'description' => 'Phiếu tự đánh giá viết.', 'preview' => 'Thiết kế phiếu tự đánh giá kỹ năng viết đoạn / bài văn cho học sinh, tập trung vào ý tưởng, bố cục, diễn đạt và chính tả.', 'uses' => 0, 'tags' => [['name'=>'Vietnamese','cat'=>'subject']]],
    ['title' => 'Hoạt động đóng vai nhân vật', 'description' => 'Đóng vai nhân vật.', 'preview' => 'Thiết kế hoạt động đóng vai một nhân vật trong tác phẩm [TÊN], kèm câu hỏi phỏng vấn và tiêu chí đánh giá sự hiểu biết về nhân vật.', 'uses' => 0, 'tags' => [['name'=>'Vietnamese','cat'=>'subject']]],
    ['title' => 'Tìm hiểu hoàn cảnh sáng tác', 'description' => 'Tìm hiểu hoàn cảnh sáng tác.', 'preview' => 'Hướng dẫn học sinh tìm hiểu và trình bày hoàn cảnh sáng tác của tác phẩm [TÊN], sau đó liên hệ với nội dung tác phẩm.', 'uses' => 0, 'tags' => [['name'=>'Vietnamese','cat'=>'subject']]],
    ['title' => 'So sánh văn học Việt – thế giới', 'description' => 'So sánh văn học Việt và thế giới.', 'preview' => 'Thiết kế hoạt động so sánh một tác phẩm / chủ đề văn học Việt Nam với một tác phẩm nước ngoài tương đồng. Cung cấp tiêu chí so sánh.', 'uses' => 0, 'tags' => [['name'=>'Vietnamese','cat'=>'subject']]],
    ['title' => 'Luyện chính tả và diễn đạt', 'description' => 'Luyện chính tả – diễn đạt.', 'preview' => 'Tạo bài tập luyện chính tả và cách diễn đạt câu dựa trên các lỗi thường gặp của học sinh lớp [KHỐI].', 'uses' => 0, 'tags' => [['name'=>'Vietnamese','cat'=>'subject']]],
    ['title' => 'Dự án nghiên cứu nhỏ về tác giả', 'description' => 'Dự án nghiên cứu tác giả.', 'preview' => 'Thiết kế một dự án nghiên cứu nhỏ về tác giả [TÊN TÁC GIẢ] cho học sinh, bao gồm các bước thực hiện, sản phẩm đầu ra và tiêu chí đánh giá.', 'uses' => 0, 'tags' => [['name'=>'Vietnamese','cat'=>'subject']]],
    ['title' => 'Phản biện ý kiến trong văn bản', 'description' => 'Phản biện ý kiến.', 'preview' => 'Tạo hoạt động yêu cầu học sinh phản biện một ý kiến / quan điểm trong văn bản nghị luận, kèm khung lập luận phản biện.', 'uses' => 0, 'tags' => [['name'=>'Vietnamese','cat'=>'subject']]],
    ['title' => 'Viết nhật ký nhân vật', 'description' => 'Viết nhật ký từ góc nhìn nhân vật.', 'preview' => 'Yêu cầu học sinh viết nhật ký từ góc nhìn của một nhân vật trong tác phẩm [TÊN]. Cung cấp gợi ý về nội dung và giọng điệu.', 'uses' => 0, 'tags' => [['name'=>'Vietnamese','cat'=>'subject']]],
    ['title' => 'Đánh giá cuối học kỳ theo năng lực', 'description' => 'Đánh giá cuối kỳ theo năng lực.', 'preview' => 'Thiết kế đề kiểm tra / nhiệm vụ đánh giá cuối học kỳ môn Ngữ văn lớp [KHỐI] theo định hướng năng lực (đọc hiểu, viết, nói-nghe), kèm rubrics.', 'uses' => 0, 'tags' => [['name'=>'Vietnamese','cat'=>'subject']]],
];

echo "Total prompts: " . count($newPrompts) . "\n";

DB::transaction(function () use ($newPrompts, $adminId) {
    foreach ($newPrompts as $p) {
        $prompt = PromptLibraryPrompt::create([
            'author_id' => $adminId,
            'title' => $p['title'],
            'description' => $p['description'],
            'preview_text' => $p['preview'],
            'uses_count' => $p['uses'],
        ]);

        $tagIds = [];
        foreach ($p['tags'] as $tagData) {
            $tag = Tag::firstOrCreate(
                ['name' => $tagData['name']],
                ['category' => $tagData['cat']]
            );
            $tagIds[] = $tag->id;
        }
        $prompt->tags()->sync($tagIds);
    }
});

echo "Done! Seeded " . count($newPrompts) . " prompts.\n";
